CREATE TABLE FINANCIAL_INSTITUTION(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  	NAME VARCHAR(255) NOT NULL
)

CREATE TABLE PORTFOLIO(
  	ID_FINANCIAL_INSTITUTION INT NOT NULL FOREIGN KEY REFERENCES FINANCIAL_INSTITUTION(ID),
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  	NAME VARCHAR(255) NOT NULL
)

CREATE TABLE FINANCIAL_INSTRUMENT(
  	ID_FINANCIAL_INSTITUTION INT NOT NULL FOREIGN KEY REFERENCES FINANCIAL_INSTITUTION(ID),
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  	ID_PORTFOLIO INT FOREIGN KEY REFERENCES PORTFOLIO(ID),
  	TYPE VARCHAR(255) NOT NULL,
  	MARKET_VALUE DECIMAL(10,2) NOT NULL
)

GO
CREATE VIEW View_FINANCIAL_INSTRUMENT_CATEGORIZED
AS
SELECT 
	ID_FINANCIAL_INSTITUTION, 
	ID, 
	ID_PORTFOLIO, 
	TYPE, 
	MARKET_VALUE, 
	CASE 
		WHEN MARKET_VALUE < 1000000 THEN 'LowValue' 
		WHEN MARKET_VALUE < 5000000 THEN 'MediumValue' 
		ELSE 'HighValue' 
	END AS CATEGORY
FROM  dbo.FINANCIAL_INSTRUMENT
GO

DECLARE @INSTITUTION_ID INT;
INSERT INTO FINANCIAL_INSTITUTION VALUES('ONE');
SET @INSTITUTION_ID = SCOPE_IDENTITY();

INSERT INTO PORTFOLIO VALUES(@INSTITUTION_ID,'Portfolio ONE');
DECLARE @PORTFOLIO_ID INT;
SET @PORTFOLIO_ID = SCOPE_IDENTITY();

INSERT INTO [dbo].[FINANCIAL_INSTRUMENT]
           ([ID_FINANCIAL_INSTITUTION]
           ,[ID_PORTFOLIO]
           ,[TYPE]
           ,[MARKET_VALUE])
     VALUES
           (@INSTITUTION_ID,
           @PORTFOLIO_ID,
           'Stock',
           800000)

INSERT INTO [dbo].[FINANCIAL_INSTRUMENT]
           ([ID_FINANCIAL_INSTITUTION]
           ,[ID_PORTFOLIO]
           ,[TYPE]
           ,[MARKET_VALUE])
     VALUES
           (@INSTITUTION_ID,
           @PORTFOLIO_ID,
           'Bond',
           1500000)

INSERT INTO [dbo].[FINANCIAL_INSTRUMENT]
           ([ID_FINANCIAL_INSTITUTION]
           ,[ID_PORTFOLIO]
           ,[TYPE]
           ,[MARKET_VALUE])
     VALUES
           (@INSTITUTION_ID,
           @PORTFOLIO_ID,
           'Derivative',
           6000000)

INSERT INTO [dbo].[FINANCIAL_INSTRUMENT]
           ([ID_FINANCIAL_INSTITUTION]
           ,[ID_PORTFOLIO]
           ,[TYPE]
           ,[MARKET_VALUE])
     VALUES
           (@INSTITUTION_ID,
           @PORTFOLIO_ID,
           'Stock',
           300000)


